export const GET_AUTHORS = 'GET_AUTHORS';
export const SET_AUTHOR_DATA = 'SET_AUTHOR_DATA';
export const SET_AUTHOR_ERRORS = 'SET_AUTHOR_ERRORS';
export const GET_AUTHOR_BY_ID = 'GET_AUTHOR_BY_ID';
export const RESET_AUTHOR = 'RESET_AUTHOR';